// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories;

public partial class PantherProfile
{
    public int PantherProfileId { get; set; }

    public int PantherTypeId { get; set; }

    public string PantherName { get; set; }

    public double Weight { get; set; }

    public string Characteristics { get; set; }

    public string Warning { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual PantherType PantherType { get; set; }
}